# Generated by scripts/release/homebrew-formula.mjs for v0.7.4. Do not edit by hand.
class Shadenet < Formula
  desc "Proof-gated Tor egress for agents (ShadeNet research preview)"
  homepage "https://github.com/dmarzzz/shade-tree-node"
  version "0.7.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.4/shadenet-0.7.4-aarch64-apple-darwin-live"
      sha256 "76ff9484d8349af657642e3435c4adb963738ce49aaca153a84545d9c16d8b88"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.4/shadenet-0.7.4-x86_64-apple-darwin-live"
      sha256 "263b7d963e834b8959ee321de3c6cfa473288d8b87809af7b3c18e985c2be837"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.4/shadenet-0.7.4-aarch64-unknown-linux-musl-live"
      sha256 "40338424784b77761f625f684f1e2191ff1159156e4c45bfe0c92897fb57349c"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.4/shadenet-0.7.4-x86_64-unknown-linux-musl-live"
      sha256 "f8743d939dfcb7a7f9144d9965ba941d167230266a04d5cae3bae9c42b484af1"
    end
  end

  def install
    bin.install Dir["shadenet-*"].first => "shadenet"
    bin.install_symlink "shadenet" => "shade-tree"
  end

  test do
    assert_match "proxy", shell_output("#{bin}/shadenet --help")
  end
end
