# Generated by scripts/release/homebrew-formula.mjs for v0.7.3. Do not edit by hand.
class Shadenet < Formula
  desc "Proof-gated Tor egress for agents (ShadeNet research preview)"
  homepage "https://github.com/dmarzzz/shade-tree-node"
  version "0.7.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.3/shadenet-0.7.3-aarch64-apple-darwin-live"
      sha256 "0df61996bb769bbeddd8b9d859a3fb3ec52994fe3bc83a432cd1847cea06e62a"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.3/shadenet-0.7.3-x86_64-apple-darwin-live"
      sha256 "aa76463e442e68cdd0295e09aa42aaae7b9e36f3c971e29136f30ba1c857a0a2"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.3/shadenet-0.7.3-aarch64-unknown-linux-musl-live"
      sha256 "c10eb2c34dfa87af3d789de3303549dc51d3a33bc7536d2c45e2b845e3d2aeee"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.3/shadenet-0.7.3-x86_64-unknown-linux-musl-live"
      sha256 "88cc07e41e168fc74040954d515f333290f3a06b3dd2627ee2e26c9686cabd71"
    end
  end

  def install
    bin.install Dir["shadenet-*"].first => "shadenet"
    bin.install_symlink "shadenet" => "shade-tree"
  end

  test do
    assert_match "proxy", shell_output("#{bin}/shadenet --help")
  end
end
