# Generated by scripts/release/homebrew-formula.mjs for v0.7.1. Do not edit by hand.
class Shadenet < Formula
  desc "Proof-gated Tor egress for agents (ShadeNet research preview)"
  homepage "https://github.com/dmarzzz/shade-tree-node"
  version "0.7.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.1/shadenet-0.7.1-aarch64-apple-darwin-live"
      sha256 "40da91c1e55ac336dd49c1617fdc4aa42d96ef5835a68cd64ad680b5b6f6cc8d"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.1/shadenet-0.7.1-x86_64-apple-darwin-live"
      sha256 "7255c5e5a9b3082a39fc79865df2ff2a7d64cc6bcb9e7abc7faff03db4bd3013"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.1/shadenet-0.7.1-aarch64-unknown-linux-musl-live"
      sha256 "da09a9b61bd8a03858fbbb360744c2aba1e2b106d7b9a562439a60e3db1f986a"
    end
    on_intel do
      url "https://github.com/dmarzzz/shade-tree-node/releases/download/v0.7.1/shadenet-0.7.1-x86_64-unknown-linux-musl-live"
      sha256 "4b3b9add3e8b090317f7a90b13ace6211147e9bd25a5ef53b0c99fd6b8012a02"
    end
  end

  def install
    bin.install Dir["shadenet-*"].first => "shadenet"
    bin.install_symlink "shadenet" => "shade-tree"
  end

  test do
    assert_match "proxy", shell_output("#{bin}/shadenet --help")
  end
end
